### PR TITLE
Use the BX:Z tag if present, and read sequence lengths from SAM header

### PR DESCRIPTION
**Pull request by sjackman**
Use the BX:Z tag if present and read name otherwise
The --bx option is retained for compatibility but otherwise ignored.

Read the FASTA sequence lengths from the SAM header
The -f FASTA file argument is optional.

### CODE REVIEW

**Comment by sjackman** [comment]
@benvvalk Can you give this PR a quick scan sanity check? If all is good, I'll tag and release version 1.0.3.

**Comment by benvvalk** [comment]
Nice :-)

Parsing the sequence lengths from the SAM headers is a nice usability improvement as well!

A couple of minor issues:
* I think you broke the unit test in `Test/ParseUtilTest.h` (run with `make check`) by removing `Common/ParseUtil.h`. I think the unit test will be handy in case we ever need to change/optimize the barcode-parsing method.  (But if you find it easiest to just remove the test, feel free.)
* I think you broke `make distcheck` by not removing `ParseUtil.h` from `Common/Makefile.am`

**Comment by sjackman** [comment]
Woops! I'll fix it.

**Comment by sjackman** [comment]
Merged!

**Comment by benvvalk** [comment]
Thanks, @sjackman!  (Thanks for fixing my StatUtilTest too!)

**Comment by sjackman** [comment]
You're test was right! It failed for me because it no longer removes the `-1` suffix after my patch.

**Pull request merged**
